# Generated by Django 5.2.10 on 2026-01-26 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('patrimonio', models.CharField(max_length=10, null=True, unique=True)),
                ('quantidade_total', models.PositiveIntegerField()),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=14, unique=True)),
                ('nome', models.CharField(max_length=75)),
                ('tipo', models.CharField(choices=[('ALUNO', 'Aluno'), ('SERVIDOR', 'Servidor')], max_length=8)),
                ('perfil', models.CharField(choices=[('COMUM', 'Comum'), ('OPERADOR', 'Operador'), ('GESTOR', 'Gestor'), ('ADMINISTRADOR', 'Administrador')], max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_saida', models.DateTimeField(auto_now_add=True)),
                ('data_devolucao', models.DateTimeField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, default='', null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos', to='inventario.material')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos', to='inventario.usuario')),
            ],
        ),
    ]
