# Generated by Django 5.2.10 on 2026-01-29 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='descricao',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='material',
            name='patrimonio',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='material',
            name='quantidade_total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
