# Generated by Django 5.2.10 on 2026-01-29 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_material_descricao_alter_material_patrimonio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='observacao',
            field=models.TextField(blank=True, default=''),
        ),
    ]
